# Generated by Django 5.0.2 on 2024-03-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='new_one.book')),
            ],
        ),
    ]
