# Generated by Django 5.0.2 on 2024-03-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_one', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
